#!/usr/bin/with-contenv bash

PUID=${PUID:-1000}
PGID=${PGID:-1000}

groupmod -o -g "$PGID" docker
usermod -o -u "$PUID" docker

echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u docker)
User gid:    $(id -g docker)
-------------------------------------
"
chown docker:docker /app
chown docker:docker /config
chown docker:docker /defaults